param([string]$OutPath = "docs/status/Nightly.md")
$ErrorActionPreference='Stop'
$dir = Split-Path -Parent $OutPath
if(!(Test-Path $dir)){ New-Item -ItemType Directory -Force $dir | Out-Null }
$utc=(Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ssZ")
$repo=try{ (Split-Path -Leaf (Get-Location)) }catch{'(unknown)'}
$branch=try{ (git rev-parse --abbrev-ref HEAD 2>$null).Trim() }catch{'(no-git)'}
$content=@"
# Nightly CoStatus — $repo
- UTC: $utc
- Branch: $branch

_Generated by tools/heartbeat/Collect-CoStatus.ps1_
"@
Set-Content -LiteralPath $OutPath -Value $content -Encoding utf8NoBOM
